### PR TITLE
Added test kitchen support

### PR DESCRIPTION
**Pull request by jdabney**
Hello, I updated your cookbook to support kitchen test. I would be grateful if you took a look.
Thank you.

### CODE REVIEW

**Comment by brauliobo** [comment]
hi @jdabney, merged your contribution! would you like to be a collaborator on this repo and on supermarket? Nowadays I don't spend too much time on this cookbook.

**Comment by jdabney** [comment]
@brauliobo I think I am interested! I had a few other things I was already planning on adding to the cookbook because we are standing up a new rt instance. Thank you for merging my change!

**Comment by brauliobo** [comment]
added you as a collaborator here and at supermarket!

please release a new version with the changes

**Comment by jdabney** [comment]
This is done! Thank you for letting me help.

**Pull request merged**
